#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include "libft.h"

int main()
{
/*	printf("ft_isalpha A: %d \n", ft_isalpha('A'));
	printf("isalpha A: %d \n", isalpha('A'));
	printf("ft_isalpha 5: %d \n", ft_isalpha('5'));
	printf("isalpha 5: %d \n", isalpha('5'));
	printf("ft_isalpha -: %d \n", ft_isalpha('-'));
	printf("isalpha -: %d \n", isalpha('-'));
	printf("-----------------------\n");
	printf("ft_isdigit A: %d \n", ft_isdigit('A'));
	printf("isdigit A: %d \n", isdigit('A'));
	printf("ft_isdigit 1: %d \n", ft_isdigit('1'));
	printf("isdigit 1: %d \n", isdigit('1'));
	printf("ft_isdigit -: %d \n", ft_isdigit('-'));
	printf("isdigit -: %d \n", isdigit('-'));
	printf("-----------------------\n");
	printf("ft_isalnum A: %d \n", ft_isalnum('A'));
	printf("isalnum A: %d \n", isalnum('A'));
	printf("ft_isalnum 6: %d \n", ft_isalnum('6'));
	printf("isalnum 6: %d \n", isalnum('6'));
	printf("ft_isalnum -: %d \n", ft_isalnum('-'));
	printf("isalnum -: %d \n", isalnum('-'));
	printf("-----------------------\n");
	printf("ft_isascii -: %d \n", ft_isascii('-'));
	printf("isascii -: %d \n", isascii('-'));
	printf("-----------------------\n");
	printf("ft_isprint NULL: %d \n", ft_isprint('NULL'));
	printf("isprint NULL: %d \n", isprint('NUII'));
	printf("-----------------------\n");
	char*	str = "abc";
	printf("ft_strlen: %zu\n", ft_strlen(str));
	printf("strlen: %zu\n", strlen(str));
	printf("-----------------------\n");
	char	strs[15] = "1234567890";
	printf("ft_memset: %s\n", (char*)ft_memset(strs, '2', 8));
	printf("memset: %s\n", (char*)memset(strs, '2', 8));
	printf("-----------------------\n");
	char	strs_b[15] = "1234567890";
	printf("ft_bzero: %s\n", strs_b);
	ft_bzero(strs_b, 1);
	printf("ft_bzero: %s\n", strs_b);
	char	strs_bz[15] = "1234567890";
	printf("bzero: %s\n", strs_bz);
	bzero(strs_bz, 1);
	printf("bzero: %s\n", strs_bz);
	printf("-----------------------\n");
	unsigned char	dst[10] = "";
	const unsigned char	src[10] = "123456";
	ft_memcpy(dst, src, 6);
	printf("ft_memcpy: %s\n", dst);
	unsigned char	dest[10] = "";
	const unsigned char	source[10] = "123456";
	memcpy(dest, source, 6);
	printf("memcpy: %s\n", dest);
	printf("-----------------------\n");
	unsigned char	src_mem[20] = "1234567890";
	ft_memmove(&src_mem[4], &src_mem[1], 2);
	printf("ft_memmove: %s\n", src_mem);
	unsigned char	src_m[20] = "1234567890";
	memmove(&src_m[4], &src_m[3], 3);
	printf("memmove: %s\n", src_m);
	printf("-----------------------\n");
    char const src_ft_strl[20] = "yello";
    char dst_ft_strl[10];
    int sz_ft = ft_strlcpy(dst_ft_strl, src_ft_strl, sizeof(dst_ft_strl));
    printf("ft_strlcpy: %s, lenght str: %d\n", dst_ft_strl, sz_ft);
    char const src_strl[20] = "yello";
    char dst_strl[10];
    int sz;
    sz =strlcpy(dst_strl, src_strl, sizeof(dst_strl));
    printf("strlcpy: %s, lenght str: %d\n", dst_strl, sz);
    printf("-----------------------\n");
    char dst_ft_cat[10] = "abc";
    const char *src_ft_cat = "987";
    dst_ft_cat[9] = '\0';
    int k = ft_strlcat(dst_ft_cat, src_ft_cat, 2);
    printf("rez ft: %d\n", k);
    printf("ft_strlcat: %s\n", dst_ft_cat);
    char dst_cat[10] = "abc";
    const char *src_cat = "987";
    dst_cat[9] = '\0';
    int j = strlcat(dst_cat, src_cat, 2);
    printf("rez: %d\n", j);
    printf("strlcat: %s\n", dst_cat);
    printf("-----------------------\n");
    const char s_ft[10] = "abcd";
    char *ptr_ft;
    ptr_ft = ft_strchr(s_ft, 'd');
    printf("ft_strchar: %c\n", *ptr_ft);
    const char s[10] = "abcd";
    char *ptr;
    ptr = strchr(s, 'd');
    printf("strchar: %c\n", *ptr);
    printf("-----------------------\n");
    char *sr_ft = "īœ˙ˀ˘¯ˇ¸¯.œ«‘––™ª•¡¶¢˜ˀ";
    char *ptrr_ft;
    ptrr_ft = ft_strrchr(sr_ft, L'–');
    printf("ft_strrchar: %ld\n", ptrr_ft - sr_ft);
    char *sr = "īœ˙ˀ˘¯ˇ¸¯.œ«‘––™ª•¡¶¢˜ˀ";
    char *ptrr;
    ptrr = strrchr(sr, L'–');
    printf("strrchar: %ld\n", ptrr - sr);
    printf("-----------------------\n");
    char *sn1_ft = "zyxbcdefgh";
    char *sn2_ft = "abcdwxyz";
    printf("ft_strncmp: %d\n", ft_strncmp(sn1_ft, sn2_ft, 0));
    char *sn1 = "zyxbcdefgh";
    char *sn2 = "abcdwxyz";
    printf("strncmp: %d\n", strncmp(sn1, sn2, 0));
    printf("-----------------------\n");
    char *smem_ft = "/|\x12\xff\x09\0\x42\042\0\42|\\";
    printf("ft_memchr: %s\n", ft_memchr(smem_ft, '\0', 12));
    char *smem =    "/|\x12\xff\x09\0\x42\042\0\42|\\";
    printf("memchr: %s\n", memchr(smem, '\0', 12));
    printf("-----------------------\n");
    char *smemc1_ft = "\xff\xaa\xde\x12";
    char *smemc2_ft = "\xff\xaa\xde\x12MACOSAAAAA";
    printf("ft_memcmp: %d\n", ft_memcmp(smemc1_ft, smemc2_ft, 4));
    char *smemc1 =    "\xff\xaa\xde\x12";
    char *smemc2 =    "\xff\xaa\xde\x12MACOSAAAAA";
    printf("memcmp: %d\n", memcmp(smemc1, smemc2, 4));
    printf("-----------------------\n");
    size_t size = 15;
    const char *lange_ft = "lorem ipsum dolor sit amet";
    const char *small_ft = "dolor";
    char *p_ft;
    p_ft = ft_strnstr(lange_ft, small_ft, size);
    printf("ft_strnstr: %s\n", p_ft);
    const char *lange = "lorem ipsum dolor sit amet";
    const char *small = "dolor";
    char *p;
    p = strnstr(lange, small, size);
    printf("strnstr: %s\n", p);
    printf("-----------------------\n");
    char *str_a_ft = "-9223372036854775808";
    printf("ft_atoi: %d\n", ft_atoi(str_a_ft));
    char *str_a = "-9223372036854775808";
    printf("atoi: %d\n", atoi(str_a));
    printf("-----------------------\n");
    char *s1_tr = "          ";
    char *s2_tr = " ";
    printf("ft_strtrim: %s\n", ft_strtrim(s1_tr, s2_tr));
    printf("-----------------------\n");
    char *s_split = "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse";
    char c = ' ';
    char **split;
    split = ft_split(s_split, c);
    printf("split0: %s\n", split[0]);
    printf("split1: %s\n", split[1]);
    printf("split2: %s\n", split[2]);
    printf("split3: %s\n", split[3]);
    printf("-----------------------\n");
    int n_itoa = 2147483647;
    printf("ft_itoa: %s\n", ft_itoa(n_itoa));
    printf("-----------------------\n");*/
    void    *a;
    t_list  *rez;
    int     b;
    int     *c;
    
    char *a_list = "hello, i'm a data";
    char c_list[50];
    t_list *rez_list;
    
    b = 42;
    a = &b;
    rez = ft_lstnew(a);
    c = rez->content;
    
    rez_list = ft_lstnew(a_list);
    
    printf("ft_lstnew, b = %d, c = %d\n", b, *c);
    printf("lit_s: a: %s;\nc: %s\n", a_list, rez_list->content);
    printf("-----------------------\n");
}
